2025-09-17 20:13:48,582 p=452467 u=user n=ansible | [WARNING]: errors were encountered during the plugin load for debug:
['community.general:>=5.0.0.debug is not a valid collection reference',
'ansible.posix:>=1.3.0.debug is not a valid collection reference']

2025-09-17 20:13:48,619 p=452467 u=user n=ansible | [WARNING]: errors were encountered during the plugin load for shell:
['community.general:>=5.0.0.shell is not a valid collection reference',
'ansible.posix:>=1.3.0.shell is not a valid collection reference']

2025-09-17 20:13:48,619 p=452467 u=user n=ansible | [WARNING]: errors were encountered during the plugin load for fail:
['community.general:>=5.0.0.fail is not a valid collection reference',
'ansible.posix:>=1.3.0.fail is not a valid collection reference']

2025-09-17 20:13:48,620 p=452467 u=user n=ansible | [WARNING]: errors were encountered during the plugin load for file:
['community.general:>=5.0.0.file is not a valid collection reference',
'ansible.posix:>=1.3.0.file is not a valid collection reference']

2025-09-17 20:13:48,622 p=452467 u=user n=ansible | [WARNING]: errors were encountered during the plugin load for stat:
['community.general:>=5.0.0.stat is not a valid collection reference',
'ansible.posix:>=1.3.0.stat is not a valid collection reference']

2025-09-17 20:13:48,624 p=452467 u=user n=ansible | [WARNING]: errors were encountered during the plugin load for template:
['community.general:>=5.0.0.template is not a valid collection reference',
'ansible.posix:>=1.3.0.template is not a valid collection reference']

2025-09-17 20:13:48,630 p=452467 u=user n=ansible | [WARNING]: errors were encountered during the plugin load for systemd:
['community.general:>=5.0.0.systemd is not a valid collection reference',
'ansible.posix:>=1.3.0.systemd is not a valid collection reference']

2025-09-17 20:13:48,631 p=452467 u=user n=ansible | [WARNING]: errors were encountered during the plugin load for command:
['community.general:>=5.0.0.command is not a valid collection reference',
'ansible.posix:>=1.3.0.command is not a valid collection reference']

2025-09-17 20:13:48,634 p=452467 u=user n=ansible | [WARNING]: errors were encountered during the plugin load for
community.general.ufw: ['community.general:>=5.0.0.ufw is not a valid
collection reference', 'ansible.posix:>=1.3.0.ufw is not a valid collection
reference']

2025-09-17 20:13:48,634 p=452467 u=user n=ansible | [WARNING]: errors were encountered during the plugin load for ufw:
['community.general:>=5.0.0.ufw is not a valid collection reference',
'ansible.posix:>=1.3.0.ufw is not a valid collection reference']

2025-09-17 20:13:48,634 p=452467 u=user n=ansible | ERROR! couldn't resolve module/action 'ufw'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/user/ansible-matlab-installer/roles/matlab-installer/handlers/main.yml': line 96, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: reload ufw
  ^ here

2025-09-17 20:14:10,349 p=452546 u=user n=ansible | ERROR! couldn't resolve module/action 'community.general.ufw'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/user/ansible-matlab-installer/roles/matlab-installer/handlers/main.yml': line 96, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: reload ufw
  ^ here

2025-09-17 20:14:19,423 p=452602 u=user n=ansible | playbook: install-matlab-linux.yml
